trigger:
  branches:
    include:
      - main

jobs:
- job: deployfunction
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - task: AWSShellScript@1
    displayName: 'Configure AWS credentials'
    inputs:
      awsCredentials: 'awsconfig'
      regionName: 'ap-south-1' # Update with your AWS region

  - script: |
      pip install awscli
      aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
      aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
      aws configure set region $(AWS_REGION)
    displayName: 'Install AWS CLI and configure credentials'

  - script: |
      if [[ $(git diff --name-only HEAD^ HEAD | grep -q 'Lambda_functions/'; echo $?) -eq 0 ]]; then
        echo "Deploying Lambda Functions..."
        for modified_folder in $(git diff --name-only HEAD^ HEAD | grep '^Lambda_functions/' | xargs -I {} dirname {} | sort -u); do
          function_folder=$(basename "$modified_folder")
          echo $function_folder
          function_name=$(basename "$function_folder")
          echo $function_name

          # Zip the function code using the extracted folder path
          zip -j "${function_name}.zip" "$function_folder"/*

          # Update the function code
          aws lambda update-function-code \
            --function-name "$function_name" \
            --zip-file "fileb://${function_name}.zip"

          new_version_number=$(aws lambda publish-version --function-name "$function_name" --query 'Version' --output text)

          # Update the "latest" alias to point to the new version
          aws lambda update-alias \
            --function-name "$function_name" \
            --name "latest" \
            --function-version "$new_version_number"
        done
      fi
    displayName: 'Deploy Lambda Functions'
