name: Deploy Lambda Functions and Layers

on:
  push:
    branches:
      - main

jobs:
  deploy-lambda-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Update with your AWS region

      - name: Deploy Lambda functions
        run: |
          for function_folder in Lambda_functions/*; do
            function_name=$(basename "$function_folder")
            aws lambda update-function-code \
              --function-name "$function_name" \
              --zip-file "fileb://${function_name}.zip"

            # Get the new version number
            new_version_number=$(aws lambda list-versions-by-function --function-name "$function_name" --max-items 1 --query 'Versions[0].Version' --output text)

            # Update the "latest" alias to point to the new version
            aws lambda update-alias \
              --function-name "$function_name" \
              --name "latest" \
              --function-version "$new_version_number"
          }

  deploy-lambda-layer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Update with your AWS region

      - name: Deploy Lambda layer
        run: |
          cd AWS_Lambda_layer
          layer_version=$(aws lambda publish-layer-version \
            --layer-name "my-lambda-layer" \
            --zip-file "fileb://layer.zip" \
            --compatible-runtimes python3.8 | jq -r '.LayerVersionArn')

          # Update all Lambda functions with the new layer version
          for function_name in $(aws lambda list-functions --max-items 1000 --query 'Functions[*].FunctionName' --output text); do
            aws lambda update-function-configuration \
              --function-name "$function_name" \
              --layers "$layer_version"
          }

# Define stages
stages:
  - deploy-functions
  - deploy-layer

# Define jobs for each stage
jobs:
  - deploy-lambda-functions:
      runs-on: ubuntu-latest
      if: github.event.commits[0].modified.paths.contains('Lambda_functions/')

  - deploy-lambda-layer:
      runs-on: ubuntu-latest
      if: github.event.commits[0].modified.paths.contains('AWS_Lambda_layer/')
